// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	adminRoleMenuFieldNames          = builder.RawFieldNames(&AdminRoleMenu{})
	adminRoleMenuRows                = strings.Join(adminRoleMenuFieldNames, ",")
	adminRoleMenuRowsExpectAutoSet   = strings.Join(stringx.Remove(adminRoleMenuFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	adminRoleMenuRowsWithPlaceHolder = strings.Join(stringx.Remove(adminRoleMenuFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"
)

type (
	adminRoleMenuModel interface {
		Insert(ctx context.Context, data *AdminRoleMenu) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AdminRoleMenu, error)
		Update(ctx context.Context, newData *AdminRoleMenu) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAdminRoleMenuModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AdminRoleMenu struct {
		Id        int64        `db:"id"`
		RoleId    int64        `db:"role_id"`
		MenuId    int64        `db:"menu_id"`
		CreatedAt sql.NullTime `db:"created_at"`
		UpdatedAt sql.NullTime `db:"updated_at"`
	}
)

func newAdminRoleMenuModel(conn sqlx.SqlConn) *defaultAdminRoleMenuModel {
	return &defaultAdminRoleMenuModel{
		conn:  conn,
		table: "`admin_role_menu`",
	}
}

func (m *defaultAdminRoleMenuModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAdminRoleMenuModel) FindOne(ctx context.Context, id int64) (*AdminRoleMenu, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", adminRoleMenuRows, m.table)
	var resp AdminRoleMenu
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminRoleMenuModel) Insert(ctx context.Context, data *AdminRoleMenu) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, adminRoleMenuRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.RoleId, data.MenuId, data.CreatedAt, data.UpdatedAt)
	return ret, err
}

func (m *defaultAdminRoleMenuModel) Update(ctx context.Context, data *AdminRoleMenu) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, adminRoleMenuRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.RoleId, data.MenuId, data.CreatedAt, data.UpdatedAt, data.Id)
	return err
}

func (m *defaultAdminRoleMenuModel) tableName() string {
	return m.table
}
