// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	invitationCodeFieldNames          = builder.RawFieldNames(&InvitationCode{})
	invitationCodeRows                = strings.Join(invitationCodeFieldNames, ",")
	invitationCodeRowsExpectAutoSet   = strings.Join(stringx.Remove(invitationCodeFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	invitationCodeRowsWithPlaceHolder = strings.Join(stringx.Remove(invitationCodeFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"
)

type (
	invitationCodeModel interface {
		Insert(ctx context.Context, data *InvitationCode) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*InvitationCode, error)
		Update(ctx context.Context, newData *InvitationCode) error
		Delete(ctx context.Context, id int64) error
	}

	defaultInvitationCodeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	InvitationCode struct {
		Id        int64          `db:"id"`
		Code      sql.NullString `db:"code"`
		Status    sql.NullInt64  `db:"status"`
		Number    sql.NullString `db:"number"`
		CreatedAt sql.NullTime   `db:"created_at"`
		UpdatedAt sql.NullTime   `db:"updated_at"`
	}
)

func newInvitationCodeModel(conn sqlx.SqlConn) *defaultInvitationCodeModel {
	return &defaultInvitationCodeModel{
		conn:  conn,
		table: "`invitation_code`",
	}
}

func (m *defaultInvitationCodeModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultInvitationCodeModel) FindOne(ctx context.Context, id int64) (*InvitationCode, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", invitationCodeRows, m.table)
	var resp InvitationCode
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultInvitationCodeModel) Insert(ctx context.Context, data *InvitationCode) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, invitationCodeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Code, data.Status, data.Number, data.CreatedAt, data.UpdatedAt)
	return ret, err
}

func (m *defaultInvitationCodeModel) Update(ctx context.Context, data *InvitationCode) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, invitationCodeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Code, data.Status, data.Number, data.CreatedAt, data.UpdatedAt, data.Id)
	return err
}

func (m *defaultInvitationCodeModel) tableName() string {
	return m.table
}
