// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	migrationsFieldNames          = builder.RawFieldNames(&Migrations{})
	migrationsRows                = strings.Join(migrationsFieldNames, ",")
	migrationsRowsExpectAutoSet   = strings.Join(stringx.Remove(migrationsFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	migrationsRowsWithPlaceHolder = strings.Join(stringx.Remove(migrationsFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"
)

type (
	migrationsModel interface {
		Insert(ctx context.Context, data *Migrations) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Migrations, error)
		Update(ctx context.Context, newData *Migrations) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMigrationsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Migrations struct {
		Id        int64  `db:"id"`
		Migration string `db:"migration"`
		Batch     int64  `db:"batch"`
	}
)

func newMigrationsModel(conn sqlx.SqlConn) *defaultMigrationsModel {
	return &defaultMigrationsModel{
		conn:  conn,
		table: "`migrations`",
	}
}

func (m *defaultMigrationsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMigrationsModel) FindOne(ctx context.Context, id int64) (*Migrations, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", migrationsRows, m.table)
	var resp Migrations
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMigrationsModel) Insert(ctx context.Context, data *Migrations) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, migrationsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Migration, data.Batch)
	return ret, err
}

func (m *defaultMigrationsModel) Update(ctx context.Context, data *Migrations) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, migrationsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Migration, data.Batch, data.Id)
	return err
}

func (m *defaultMigrationsModel) tableName() string {
	return m.table
}
